serviceAccount:
  create: true
  name: redash-sa
  annotations: {} # Managed by Terraform

postgresql:
  enabled: true
  image:
    registry: 827913617635.dkr.ecr.ap-northeast-2.amazonaws.com
    repository: capa/postgres
    tag: "11"
  postgresqlUsername: "redash"
  postgresqlDatabase: "redash"
  postgresqlPassword: "" # Managed by Terraform (set_sensitive)
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  primary:
    nodeSelector:
      node-type: core

redis:
  enabled: true
  image:
    registry: 827913617635.dkr.ecr.ap-northeast-2.amazonaws.com
    repository: capa/redis
    tag: "6.0.9"
  auth:
    enabled: false
    password: "" # 빈 문자열로 명시하여 Redash가 비밀번호 없이 연결하도록 강제
  master:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    nodeSelector:
      node-type: core

server:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 768Mi
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 15
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 20
  nodeSelector:
    node-type: core

scheduler:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector:
    node-type: core

adhocWorker:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

scheduledWorker:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

genericWorker:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

service:
  type: ClusterIP
  port: 5000
